cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/services"

brew "awscli"
brew "imagemagick@6", link: true
brew "mongodb", restart_service: true
brew "node"
brew "postgresql"
brew "yarn"
brew "bat"

cask "atom"
cask "firefox"
cask "mongodb-compass"
cask "postico"
cask "postman"
cask "wkhtmltopdf"
