#! /bin/bash

set -e

SECRET_KEY=$1

if [ -z "${SECRET_KEY}" ] ; then
	echo "Usage: credentials ACCOUNT_KEY"
	exit 1
fi

echo "Signing into 1P..."
op signin rodas.1password.com jaime@rodas.mx $SECRET_KEY --output=raw &> /dev/null
eval $(op signin rodas)

echo "Making sure ~/.ssh exists..."
mkdir -p ~/.ssh
rm -f ~/.ssh/id_rsa*

echo "Creating id_rsa..."
op get document id_rsa >> ~/.ssh/id_rsa

echo "Creating id_rsa.pub..."
op get document id_rsa.pub >> ~/.ssh/id_rsa.pub

echo "Setting permissions..."
chmod 600 ~/.ssh/id_rsa*

echo "All done!"
