#! /bin/bash

set -e

SUBDOMAIN=rodas
ACCOUNT_EMAIL="jaime@rodas.mx"

echo "Credentials installer"
read -p "Enter your 1Password Account Key: " SECRET_KEY
read -s -p "Enter your 1Password Master Password: " MASTER_PASSWORD
echo ""
echo "---------------------------"

echo "Signing into 1P..."
eval $(op signin "$SUBDOMAIN.1password.com" "$ACCOUNT_EMAIL" "$SECRET_KEY" "$MASTER_PASSWORD")

echo "Making sure ~/.ssh exists..."
mkdir -p ~/.ssh
rm -f ~/.ssh/id_rsa*

printf "Creating id_rsa..."
op get document id_rsa >> ~/.ssh/id_rsa
echo " (success)"

printf "Creating id_rsa.pub..."
op get document id_rsa.pub >> ~/.ssh/id_rsa.pub
echo " (success)"

echo "Setting permissions..."
chmod 600 ~/.ssh/id_rsa*

echo "All done!"
