#! /bin/bash

set -e

SECRET_KEY=$1

if [ -z "${SECRET_KEY}" ] ; then
	echo "Usage: credentials ACCOUNT_KEY"
	exit 1
fi

op signin rodas.1password.com jaime@rodas.mx $SECRET_KEY --output=raw &> /dev/null

mkdir -p ~/.ssh
rm -f ~/.ssh/id_rsa*

op get document id_rsa >> ~/.ssh/id_rsa
op get document id_rsa.pub >> ~/.ssh/id_rsa.pub

chmod 600 ~/.ssh/id_rsa*
