#! /bin/bash

set -e

# Install xCode Tools
XCODE_INSTALLED=$(xcode-select -p)
if [ -x $XCODE_INSTALLED ]; then
	echo "xcode-tools already installed, skipping..."
else
	echo "installing xcode-tools..."
	xcode-select --install
fi
echo ----------------------

# Update software and restart the computer if necessary
echo Updating system software...
softwareupdate --install --all --restart
echo ----------------------

echo Installing dotfiles...
cd ~/
sudo rm -rf .dotfiles && git clone https://github.com/jaimerodas/.dotfiles.git
.dotfiles/setup

