#!/bin/bash

set -e

action=$1
environment_name=${2:-encontaapp-production}
username=ec2-user
pem_file=~/.ssh/$environment_name.pem
bold=$(tput bold)
normal=$(tput sgr0)

function connect {
	echo "Buscando servidores de entorno ${bold}$environment_name${normal}"
	pids=""
	for server in $(servers); do
		echo "Cargando logs de ${bold}$server${normal}"
		ssh -n -i "$pem_file" "$username@$server" tail -f /var/app/current/log/*.log &
		pids="$pids $!"
	done

	trap 'kill -9 $pids' SIGINT
}

function servers {
	aws elasticbeanstalk describe-environment-resources --environment-name "$environment_name" | 
		grep INSTANCES | 
		awk '{print $2}' | 
		xargs aws ec2 describe-instances --instance-ids | 
		grep INSTANCES | 
		awk '{print $15}'
}

case "$action" in
	tail)
		connect
		;;
	list)
		echo "Buscando servidores de entorno ${bold}$environment_name${normal}"
		servers
		;;
	*)
		echo "Cómo usar esto:"
		echo "	eb-info -h                              		Muestra este mensaje"
		echo "	eb-info tail [entorno=enconta-production]		Empieza el tail"
		echo "	eb-info list [entorno=enconta-production]		Lista los hosts"
		;;
esac
